### ISSUE TITLE
Week 2: Complete hill definiations

### ISSUE THREAD

**Issue by omkarID** [IITIDIDX597/sp_2021_team3#8]
@omkarID @lmcclure1 @mgokani1201 to come up with hill definition for for the terms finalized for the 5:15pm meeting on Mon, Jan 25, 2021

https://app.mural.co/t/iitidagilecourseworkspace6801/m/iitidagilecourseworkspace6801/1610654383254/fc21457cb18c5d9726add7cb23954e29ccef4b1e

**Comment by mgokani1201** [comment]
@omkarID @lmcclure1 started working on this...

**Comment by mgokani1201** [comment]
@lmcclure1 @omkarID i have finished my parts and added some leading thoughts on some of yours too.

**Comment by lmcclure1** [comment]
@mgokani1201 @omkarID working on these now. thanks for adding notes!

**Comment by lmcclure1** [comment]
@mgokani1201 great idea to take a pass at writing something for each of the definitions. it helped orient my thoughts for all. I've completed this task

**Comment by omkarID** [comment]
@lmcclure1 @mgokani1201 I will get done by 1pm today.

**Comment by omkarID** [comment]
@lmcclure1 @mgokani1201 added my take on the definitions. Kept the language specific to Airbnb but generic enough so that they aren't too restrictive. 

Moving this task to Done.

**Comment by akallish** [comment]
@lmcclure1 @mgokani1201 @omkarID I reviewed your hills mural and the goal statement is good, but upon reviewing the deck to me some key things seemed to be missing. Here is a revised goal to consider :

"Airbnb One provides unique curated spaces that cater to flexible work/life needs in order to elevate productivity as healthy, motivational and inspiring."

Only a suggestion. 

Keep up the good work!
